version: "3.9"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - phpwebserver

  php-fpm:
    build: ./docker/php/
    working_dir: /var/www/html
    expose:
      - 9000
    volumes:
      - ./:/var/www/html
      - ./dev/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./dev/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - phpwebserver

networks:
  phpwebserver:
    name: phpwebserver.net
